pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./node_modules
    volumes:
      - /tmp/cache:/cache
  build:
    image: node:10-alpine
    commands:
      - npm ci
      - npm run build
  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./node_modules
    volumes:
      - /tmp/cache:/cache
  build-notify:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    username: Drone
    when:
      status: [ success, failure ]
    template: >
      {{#success build.status}}
        build {{build.number}} succeeded. Good job.
      {{else}}
        build {{build.number}} failed. Fix me please.
      {{/success}}
      CommitID: {{build.commit}}
      URL: https://drone.syuchan.work/{{repo.owner}}/{{repo.name}}/{{build.number}}
  scp:
    image: appleboy/drone-scp
    host: 192.168.1.251
    username: drone
    password: drone
    source: dist/*
    strip_components: 1
    # https://github.com/appleboy/drone-scp/issues/30
    target: /Server/School/Drone/frontend/${DRONE_COMMIT_SHA:0:7}
    when:
      status: [ success ]
  ssh:
    image: appleboy/drone-ssh
    host: 192.168.1.251
    username: drone
    password: drone
    script:
      - unlink /Server/School/Drone/frontend/latest
      - cd /Server/School/Drone/frontend && ln -s ./${DRONE_COMMIT_SHA:0:7} ./latest
  deploy-notify:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    username: Drone
    when:
      status: [ success, failure ]
    template: >
      {{#success build.status}}
        Deploy Complete! http://{{truncate build.commit 7}}.frontend.syuchan.work
      {{else}}
        deploy failed.
      {{/success}}
